apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-staging
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instavote
  source:
    path: staging
    repoURL: https://github.com/bholahnath/argo-labs.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
